services:
  app:
    image: php:8.3-cli
    container_name: php_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t /var/www/html
    ports:
      - "8000:8000"
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    entrypoint: >
      sh -c "
      if [ ! -f /usr/bin/composer ]; then
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer;
      fi;
      composer install;
      php -S 0.0.0.0:8000 -t /var/www/html
      "